In [2]:
'''7.1Write a program to create a dataframe ‘data’ containing the data from the following dataset
“https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv”.'''
import pandas as pd

# URL of the dataset
df = "Cars93_miss.csv"

# Read the dataset into a DataFrame
data = pd.read_csv(df)

# Display the first few rows of the DataFrame
print(data.head())

  Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0
2         Audi       90  Compact       25.9   29.1       32.3      20.0
3         Audi      100  Midsize        NaN   37.7       44.6      19.0
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0
1         25.0  Driver & Passenger      Front  ...        5.0   195.0
2         26.0         Driver only      Front  ...        5.0   180.0
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0
4         30.0                 NaN       Rear  ...        4.0   186.0

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0
1      115.0   71.0         38.0           30.0          15.0  3560.0
2      102.0   67.0         37.0           28.0          14.0  3375.0
3      106.0    NaN         37.0           31.0          17.0  3405.0
4      109.0   69.0         39.0           27.0          13.0  3640.0

    Origin           Make
0  non-USA  Acura Integra
1  non-USA   Acura Legend
2  non-USA        Audi 90
3  non-USA       Audi 100
4  non-USA       BMW 535i

[5 rows x 27 columns]

In [3]:
'''7.1Write a program and consider given a dataframe ‘data’ with missing values, use the .dropna() method to
remove all rows containing missing values. Display the resulting dataframe. Also verify the same by printing
the summary reports. Also print the rest rows and columns summary.'''
import pandas as pd

# Assuming 'data' is the DataFrame with missing values

# Display summary report before removing missing values
print("Summary report before removing missing values:")
print(data.info())
print("\n")

# Display DataFrame before removing missing values
print("DataFrame before removing missing values:")
print(data.head())
print("\n")

# Remove rows with missing values using dropna()
data_cleaned = data.dropna()

# Display resulting DataFrame after removing missing values
print("DataFrame after removing missing values:")
print(data_cleaned.head())
print("\n")

# Display summary report after removing missing values
print("Summary report after removing missing values:")
print(data_cleaned.info())

Summary report before removing missing values:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Manufacturer        89 non-null     object
 1   Model               92 non-null     object
 2   Type                90 non-null     object
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             55 non-null     object
 9   DriveTrain          86 non-null     object
 10  Cylinders           88 non-null     object
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     object
 16  Fuel.tank.capacity  85 non-null     float64
 17  Passengers          91 non-null     float64
 18  Length              89 non-null     float64
 19  Wheelbase           92 non-null     float64
 20  Width               87 non-null     float64
 21  Turn.circle         88 non-null     float64
 22  Rear.seat.room      89 non-null     float64
 23  Luggage.room        74 non-null     float64
 24  Weight              86 non-null     float64
 25  Origin              88 non-null     object
 26  Make                90 non-null     object
dtypes: float64(18), object(9)
memory usage: 19.7+ KB
None


DataFrame before removing missing values:
  Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0
2         Audi       90  Compact       25.9   29.1       32.3      20.0
3         Audi      100  Midsize        NaN   37.7       44.6      19.0
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0
1         25.0  Driver & Passenger      Front  ...        5.0   195.0
2         26.0         Driver only      Front  ...        5.0   180.0
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0
4         30.0                 NaN       Rear  ...        4.0   186.0

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0
1      115.0   71.0         38.0           30.0          15.0  3560.0
2      102.0   67.0         37.0           28.0          14.0  3375.0
3      106.0    NaN         37.0           31.0          17.0  3405.0
4      109.0   69.0         39.0           27.0          13.0  3640.0

    Origin           Make
0  non-USA  Acura Integra
1  non-USA   Acura Legend
2  non-USA        Audi 90
3  non-USA       Audi 100
4  non-USA       BMW 535i

[5 rows x 27 columns]


DataFrame after removing missing values:
   Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
2          Audi          90  Compact       25.9   29.1       32.3      20.0
7         Buick  Roadmaster    Large       22.6   23.7       24.9      16.0
17    Chevrolet     Caprice    Large       18.0   18.8       19.6      17.0
20     Chrysler     LeBaron  Compact       14.5   15.8       17.1      23.0
21     Chrysler    Imperial    Large       29.5   29.5       29.5      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
2          26.0         Driver only      Front  ...        5.0   180.0
7          25.0         Driver only       Rear  ...        6.0   216.0
17         26.0         Driver only       Rear  ...        6.0   214.0
20         28.0  Driver & Passenger      Front  ...        6.0   183.0
21         26.0         Driver only      Front  ...        6.0   203.0

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
2       102.0   67.0         37.0           28.0          14.0  3375.0
7       116.0   78.0         45.0           30.5          21.0  4105.0
17      116.0   77.0         42.0           29.5          20.0  3910.0
20      104.0   68.0         41.0           30.5          14.0  3085.0
21      110.0   69.0         44.0           36.0          17.0  3570.0

     Origin               Make
2   non-USA            Audi 90
7       USA   Buick Roadmaster
17      USA  Chevrolet Caprice
20      USA   Chrysler LeBaron
21      USA  Chrysler Imperial

[5 rows x 27 columns]


Summary report after removing missing values:
<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, 2 to 76
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Manufacturer        8 non-null      object
 1   Model               8 non-null      object
 2   Type                8 non-null      object
 3   Min.Price           8 non-null      float64
 4   Price               8 non-null      float64
 5   Max.Price           8 non-null      float64
 6   MPG.city            8 non-null      float64
 7   MPG.highway         8 non-null      float64
 8   AirBags             8 non-null      object
 9   DriveTrain          8 non-null      object
 10  Cylinders           8 non-null      object
 11  EngineSize          8 non-null      float64
 12  Horsepower          8 non-null      float64
 13  RPM                 8 non-null      float64
 14  Rev.per.mile        8 non-null      float64
 15  Man.trans.avail     8 non-null      object
 16  Fuel.tank.capacity  8 non-null      float64
 17  Passengers          8 non-null      float64
 18  Length              8 non-null      float64
 19  Wheelbase           8 non-null      float64
 20  Width               8 non-null      float64
 21  Turn.circle         8 non-null      float64
 22  Rear.seat.room      8 non-null      float64
 23  Luggage.room        8 non-null      float64
 24  Weight              8 non-null      float64
 25  Origin              8 non-null      object
 26  Make                8 non-null      object
dtypes: float64(18), object(9)
memory usage: 1.8+ KB
None

In [4]:
'''1.Write a program and consider the above dataframe with missing values, calculate the percentage of
missing values in each column and create a summary table showing the columns with the highest
percentage of missing values.'''
import pandas as pd

# Calculate percentage of missing values in each column
missing_percentages = (data.isnull().sum() / len(data)) * 100

# Create a summary table
summary_table = pd.DataFrame({
    'Column': missing_percentages.index,
    'Percentage of Missing Values': missing_percentages.values
})

# Sort summary table by percentage of missing values in descending order
summary_table = summary_table.sort_values(by='Percentage of Missing Values', ascending=False)

# Display the summary table
print(summary_table)

                Column  Percentage of Missing Values
8              AirBags                     40.860215
23        Luggage.room                     20.430108
6             MPG.city                      9.677419
16  Fuel.tank.capacity                      8.602151
9           DriveTrain                      7.526882
12          Horsepower                      7.526882
3            Min.Price                      7.526882
24              Weight                      7.526882
14        Rev.per.mile                      6.451613
20               Width                      6.451613
10           Cylinders                      5.376344
21         Turn.circle                      5.376344
5            Max.Price                      5.376344
15     Man.trans.avail                      5.376344
25              Origin                      5.376344
22      Rear.seat.room                      4.301075
18              Length                      4.301075
0         Manufacturer                      4.301075
13                 RPM                      3.225806
2                 Type                      3.225806
26                Make                      3.225806
17          Passengers                      2.150538
11          EngineSize                      2.150538
7          MPG.highway                      2.150538
4                Price                      2.150538
19           Wheelbase                      1.075269
1                Model                      1.075269

In [5]:
'''2. Write a program and consider the above dataframe, calculate and display the number of missing values
in each column individually. Sort the columns by the number of missing values in descending order.
'''
import pandas as pd

# Assuming 'data' is the DataFrame with missing values

# Calculate number of missing values in each column
missing_count = data.isnull().sum()

# Create a DataFrame for missing value counts
missing_count_df = pd.DataFrame({
    'Column': missing_count.index,
    'Missing Values Count': missing_count.values
})

# Sort columns by number of missing values in descending order
missing_count_df = missing_count_df.sort_values(by='Missing Values Count', ascending=False)

# Display the number of missing values in each column
print("Number of missing values in each column (sorted by count in descending order):")
print(missing_count_df)

Number of missing values in each column (sorted by count in descending order):
                Column  Missing Values Count
8              AirBags                    38
23        Luggage.room                    19
6             MPG.city                     9
16  Fuel.tank.capacity                     8
9           DriveTrain                     7
12          Horsepower                     7
3            Min.Price                     7
24              Weight                     7
14        Rev.per.mile                     6
20               Width                     6
10           Cylinders                     5
21         Turn.circle                     5
5            Max.Price                     5
15     Man.trans.avail                     5
25              Origin                     5
22      Rear.seat.room                     4
18              Length                     4
0         Manufacturer                     4
13                 RPM                     3
2                 Type                     3
26                Make                     3
17          Passengers                     2
11          EngineSize                     2
7          MPG.highway                     2
4                Price                     2
19           Wheelbase                     1
1                Model                     1

In [6]:
'''3. Write a program and consider the above dataframe, calculate and display the number of missing values
in each row individually. Sort the rows by the number of missing values in ascending order.
'''
import pandas as pd

missing_count_per_row = data.isnull().sum(axis=1)


missing_count_per_row_df = pd.DataFrame({
    'Row': data.index,
    'Missing Values Count': missing_count_per_row.values
})

missing_count_per_row_df = missing_count_per_row_df.sort_values(by='Missing Values Count')


print("Number of missing values in each row (sorted by count in ascending order):")
print(missing_count_per_row_df)

Number of missing values in each row (sorted by count in ascending order):
    Row  Missing Values Count
64   64                     0
2     2                     0
21   21                     0
20   20                     0
54   54                     0
..  ...                   ...
32   32                     4
56   56                     5
73   73                     5
3     3                     5
14   14                     5

[93 rows x 2 columns]

In [7]:
'''4.Write a program and consider above dataframe with missing values, remove all columns containing
missing values. Display the resulting dataframe.'''
import pandas as pd



data_without_missing_columns = data.dropna(axis=1)


print("Resulting DataFrame after removing columns with missing values:")
print(data_without_missing_columns)

Resulting DataFrame after removing columns with missing values:
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92]

[93 rows x 0 columns]

In [8]:
'''5.Write a program and consider above dataframe, remove rows that have more than a specified number
of missing values. Display the resulting dataframe.'''
import pandas as pd

# Assuming 'data' is the DataFrame with missing values

threshold_missing_values = 2

missing_values_per_row = data.isnull().sum(axis=1)

data_filtered = data[missing_values_per_row <= threshold_missing_values]

print("Resulting DataFrame after removing rows with more than {} missing values:".format(threshold_missing_values))
print(data_filtered)

Resulting DataFrame after removing rows with more than 2 missing values:
   Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura     Integra    Small       12.9   15.9       18.8      25.0
1           NaN      Legend  Midsize       29.2   33.9       38.7      18.0
2          Audi          90  Compact       25.9   29.1       32.3      20.0
5         Buick     Century  Midsize       14.2   15.7       17.3      22.0
7         Buick  Roadmaster    Large       22.6   23.7       24.9      16.0
..          ...         ...      ...        ...    ...        ...       ...
87   Volkswagen         Fox    Small        8.7    9.1        9.5      25.0
89   Volkswagen      Passat  Compact       17.6   20.0       22.4      21.0
90   Volkswagen     Corrado   Sporty       22.9   23.3       23.7      18.0
91        Volvo         240  Compact       21.8   22.7       23.5      21.0
92          NaN         850  Midsize       24.8   26.7       28.5      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
5          31.0         Driver only        NaN  ...        6.0   189.0
7          25.0         Driver only       Rear  ...        6.0   216.0
..          ...                 ...        ...  ...        ...     ...
87         33.0                 NaN      Front  ...        4.0   163.0
89         30.0                 NaN      Front  ...        5.0   180.0
90         25.0                 NaN      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0
1       115.0   71.0         38.0           30.0          15.0  3560.0
2       102.0   67.0         37.0           28.0          14.0  3375.0
5       105.0   69.0         41.0           28.0          16.0     NaN
7       116.0   78.0         45.0           30.5          21.0  4105.0
..        ...    ...          ...            ...           ...     ...
87       93.0   63.0         34.0           26.0          10.0  2240.0
89      103.0   67.0         35.0           31.5          14.0  2985.0
90       97.0   66.0         36.0           26.0          15.0  2810.0
91      104.0   67.0         37.0           29.5          14.0  2985.0
92      105.0   69.0         38.0           30.0          15.0  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
5       USA       Buick Century
7       USA    Buick Roadmaster
..      ...                 ...
87  non-USA      Volkswagen Fox
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[69 rows x 27 columns]

In [9]:
'''6. Write a program to create a summary report that includes information about the number of rows and
columns removed due to missing values after removal operations'''
import pandas as pd

rows_before, cols_before = data.shape

data_cleaned_rows = data.dropna()
rows_after_rows_removed, cols_after_rows_removed = data_cleaned_rows.shape

data_cleaned_columns = data.dropna(axis=1)
rows_after_columns_removed, cols_after_columns_removed = data_cleaned_columns.shape

rows_removed_due_to_missing_values = rows_before - rows_after_rows_removed
cols_removed_due_to_missing_values = cols_before - cols_after_columns_removed

summary_report = f"""
Summary Report:
- Number of rows removed due to missing values: {rows_removed_due_to_missing_values}
- Number of columns removed due to missing values: {cols_removed_due_to_missing_values}
"""

print(summary_report)

Summary Report:
- Number of rows removed due to missing values: 85
- Number of columns removed due to missing values: 27

In [10]:
'''7.2 Handling missing values - Imputation
Write a program to impute the missing values in the numerical column of the given dataframe ‘data’ with
the mean of the non-missing values.'''
import pandas as pd

numerical_columns_with_missing = data.select_dtypes(include='number').columns[data.select_dtypes(include='number').isnull().any()]

for column in numerical_columns_with_missing:
    mean_value = data[column].mean()
    data[column].fillna(mean_value, inplace=True)

print("DataFrame after imputing missing values with the mean:")
print(data)

DataFrame after imputing missing values with the mean:
   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                 NaN      Front  ...        7.0   187.0
89         30.0                 NaN      Front  ...        5.0   180.0
90         25.0                 NaN      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase      Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0  68.000000         37.0           26.5     13.986486  2705.0
1       115.0  71.000000         38.0           30.0     15.000000  3560.0
2       102.0  67.000000         37.0           28.0     14.000000  3375.0
3       106.0  69.448276         37.0           31.0     17.000000  3405.0
4       109.0  69.000000         39.0           27.0     13.000000  3640.0
..        ...        ...          ...            ...           ...     ...
88      115.0  72.000000         38.0           34.0     13.986486  3960.0
89      103.0  67.000000         35.0           31.5     14.000000  2985.0
90       97.0  66.000000         36.0           26.0     15.000000  2810.0
91      104.0  67.000000         37.0           29.5     14.000000  2985.0
92      105.0  69.000000         38.0           30.0     15.000000  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]

In [11]:
'''1. Write a program and consider given dataframe with missing values in a numerical column, impute the
missing values in that column with the median of the non-missing values.'''
import pandas as pd

# Assuming 'data' is the DataFrame with missing values in a numerical column

numerical_column = 'Min.Price'  # Replace 'YourNumericalColumn' with the column name having missing values

median_value = data[numerical_column].median()
data[numerical_column].fillna(median_value, inplace=True)

print(data)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                 NaN      Front  ...        7.0   187.0
89         30.0                 NaN      Front  ...        5.0   180.0
90         25.0                 NaN      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase      Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0  68.000000         37.0           26.5     13.986486  2705.0
1       115.0  71.000000         38.0           30.0     15.000000  3560.0
2       102.0  67.000000         37.0           28.0     14.000000  3375.0
3       106.0  69.448276         37.0           31.0     17.000000  3405.0
4       109.0  69.000000         39.0           27.0     13.000000  3640.0
..        ...        ...          ...            ...           ...     ...
88      115.0  72.000000         38.0           34.0     13.986486  3960.0
89      103.0  67.000000         35.0           31.5     14.000000  2985.0
90       97.0  66.000000         36.0           26.0     15.000000  2810.0
91      104.0  67.000000         37.0           29.5     14.000000  2985.0
92      105.0  69.000000         38.0           30.0     15.000000  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]

In [12]:
'''2. Write a program and consider given dataframe with missing values in a numerical column, impute the
missing values in that column with the median of the non-missing values.'''
import pandas as pd

# Assuming 'data' is the DataFrame with missing values in a numerical column

numerical_column = 'Min.Price'  # Replace 'YourNumericalColumn' with the column name having missing values

median_value = data[numerical_column].median()
data[numerical_column].fillna(median_value, inplace=True)

print(data)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                 NaN      Front  ...        7.0   187.0
89         30.0                 NaN      Front  ...        5.0   180.0
90         25.0                 NaN      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase      Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0  68.000000         37.0           26.5     13.986486  2705.0
1       115.0  71.000000         38.0           30.0     15.000000  3560.0
2       102.0  67.000000         37.0           28.0     14.000000  3375.0
3       106.0  69.448276         37.0           31.0     17.000000  3405.0
4       109.0  69.000000         39.0           27.0     13.000000  3640.0
..        ...        ...          ...            ...           ...     ...
88      115.0  72.000000         38.0           34.0     13.986486  3960.0
89      103.0  67.000000         35.0           31.5     14.000000  2985.0
90       97.0  66.000000         36.0           26.0     15.000000  2810.0
91      104.0  67.000000         37.0           29.5     14.000000  2985.0
92      105.0  69.000000         38.0           30.0     15.000000  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]

In [13]:
'''3. Write a program and consider given dataframe with missing values, impute missing values in a specific
column with a constant value of your choice (e.g., 0).'''

import pandas as pd

# Assuming 'data' is the DataFrame with missing values

# Replace 'YourColumn' with the column name where you want to impute constant values
column_to_impute = 'Min.Price'
constant_value = 1  # Change this value to the constant you want to use for imputation

data[column_to_impute].fillna(constant_value, inplace=True)

print(data)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                 NaN      Front  ...        7.0   187.0
89         30.0                 NaN      Front  ...        5.0   180.0
90         25.0                 NaN      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase      Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0  68.000000         37.0           26.5     13.986486  2705.0
1       115.0  71.000000         38.0           30.0     15.000000  3560.0
2       102.0  67.000000         37.0           28.0     14.000000  3375.0
3       106.0  69.448276         37.0           31.0     17.000000  3405.0
4       109.0  69.000000         39.0           27.0     13.000000  3640.0
..        ...        ...          ...            ...           ...     ...
88      115.0  72.000000         38.0           34.0     13.986486  3960.0
89      103.0  67.000000         35.0           31.5     14.000000  2985.0
90       97.0  66.000000         36.0           26.0     15.000000  2810.0
91      104.0  67.000000         37.0           29.5     14.000000  2985.0
92      105.0  69.000000         38.0           30.0     15.000000  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]

In [14]:
'''7.3 Handling missing values - Interpolation
Write a program and consider the given dataframe with missing values in a numerical column, use linear
interpolation to impute the missing values in that column. '''
import pandas as pd

# Assuming 'data' is the DataFrame with missing values in a numerical column

# Replace 'YourNumericalColumn' with the column name having missing values
numerical_column = 'Min.Price'

data[numerical_column] = data[numerical_column].interpolate(method='linear')

print(data)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                 NaN      Front  ...        7.0   187.0
89         30.0                 NaN      Front  ...        5.0   180.0
90         25.0                 NaN      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase      Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0  68.000000         37.0           26.5     13.986486  2705.0
1       115.0  71.000000         38.0           30.0     15.000000  3560.0
2       102.0  67.000000         37.0           28.0     14.000000  3375.0
3       106.0  69.448276         37.0           31.0     17.000000  3405.0
4       109.0  69.000000         39.0           27.0     13.000000  3640.0
..        ...        ...          ...            ...           ...     ...
88      115.0  72.000000         38.0           34.0     13.986486  3960.0
89      103.0  67.000000         35.0           31.5     14.000000  2985.0
90       97.0  66.000000         36.0           26.0     15.000000  2810.0
91      104.0  67.000000         37.0           29.5     14.000000  2985.0
92      105.0  69.000000         38.0           30.0     15.000000  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]

In [15]:
'''1. Write a program to define a custom interpolation function that takes into account domain-specific
knowledge or specific data characteristics to impute missing values in a dataframe.'''
import pandas as pd
def custom_interpolation(column):
    return column.interpolate(method='linear')

# Apply the custom interpolation function to the DataFrame
data_imputed = data.apply(custom_interpolation, axis=0)

print(data_imputed)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                 NaN      Front  ...        7.0   187.0
89         30.0                 NaN      Front  ...        5.0   180.0
90         25.0                 NaN      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase      Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0  68.000000         37.0           26.5     13.986486  2705.0
1       115.0  71.000000         38.0           30.0     15.000000  3560.0
2       102.0  67.000000         37.0           28.0     14.000000  3375.0
3       106.0  69.448276         37.0           31.0     17.000000  3405.0
4       109.0  69.000000         39.0           27.0     13.000000  3640.0
..        ...        ...          ...            ...           ...     ...
88      115.0  72.000000         38.0           34.0     13.986486  3960.0
89      103.0  67.000000         35.0           31.5     14.000000  2985.0
90       97.0  66.000000         36.0           26.0     15.000000  2810.0
91      104.0  67.000000         37.0           29.5     14.000000  2985.0
92      105.0  69.000000         38.0           30.0     15.000000  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]

C:\Users\sai raj\AppData\Local\Temp\ipykernel_2560\2129071424.py:5: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  return column.interpolate(method='linear')

In [16]:
'''2. Write a program and consider given dataframe with time-ordered data and a numerical column
containing missing values, impute the missing values in that column. Ensure that missing values are filled
with the previously available value in the column. Perform Forward Fill using forward fill (.ffill()) method'''
import pandas as pd

# Assuming 'data' is the DataFrame with time-ordered data and missing values in a numerical column

# Replace 'YourNumericalColumn' with the column name having missing values
numerical_column = 'Min.Price'

# Impute missing values using forward fill (ffill)
data[numerical_column] = data[numerical_column].ffill()

print(data)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                 NaN      Front  ...        7.0   187.0
89         30.0                 NaN      Front  ...        5.0   180.0
90         25.0                 NaN      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase      Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0  68.000000         37.0           26.5     13.986486  2705.0
1       115.0  71.000000         38.0           30.0     15.000000  3560.0
2       102.0  67.000000         37.0           28.0     14.000000  3375.0
3       106.0  69.448276         37.0           31.0     17.000000  3405.0
4       109.0  69.000000         39.0           27.0     13.000000  3640.0
..        ...        ...          ...            ...           ...     ...
88      115.0  72.000000         38.0           34.0     13.986486  3960.0
89      103.0  67.000000         35.0           31.5     14.000000  2985.0
90       97.0  66.000000         36.0           26.0     15.000000  2810.0
91      104.0  67.000000         37.0           29.5     14.000000  2985.0
92      105.0  69.000000         38.0           30.0     15.000000  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]

In [17]:
'''3. Write a program and consider given a dataframe with multiple columns, use forward fill to impute missing
values in specific columns of your choice while keeping other columns unaffected.'''
import pandas as pd

# Assuming 'data' is the DataFrame with missing values

# Replace 'columns_to_ffill' with a list of column names where you want to perform forward fill
columns_to_ffill = ['Min.Price', 'Turn.circle']  # Add column names of your choice

# Impute missing values using forward fill for specific columns
data[columns_to_ffill] = data[columns_to_ffill].ffill()

print(data)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0
..          ...      ...      ...        ...    ...        ...       ...
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0
1          25.0  Driver & Passenger      Front  ...        5.0   195.0
2          26.0         Driver only      Front  ...        5.0   180.0
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0
4          30.0                 NaN       Rear  ...        4.0   186.0
..          ...                 ...        ...  ...        ...     ...
88         21.0                 NaN      Front  ...        7.0   187.0
89         30.0                 NaN      Front  ...        5.0   180.0
90         25.0                 NaN      Front  ...        4.0   159.0
91         28.0         Driver only       Rear  ...        5.0   190.0
92         28.0  Driver & Passenger      Front  ...        5.0   184.0

    Wheelbase      Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0  68.000000         37.0           26.5     13.986486  2705.0
1       115.0  71.000000         38.0           30.0     15.000000  3560.0
2       102.0  67.000000         37.0           28.0     14.000000  3375.0
3       106.0  69.448276         37.0           31.0     17.000000  3405.0
4       109.0  69.000000         39.0           27.0     13.000000  3640.0
..        ...        ...          ...            ...           ...     ...
88      115.0  72.000000         38.0           34.0     13.986486  3960.0
89      103.0  67.000000         35.0           31.5     14.000000  2985.0
90       97.0  66.000000         36.0           26.0     15.000000  2810.0
91      104.0  67.000000         37.0           29.5     14.000000  2985.0
92      105.0  69.000000         38.0           30.0     15.000000  3245.0

     Origin                Make
0   non-USA       Acura Integra
1   non-USA        Acura Legend
2   non-USA             Audi 90
3   non-USA            Audi 100
4   non-USA            BMW 535i
..      ...                 ...
88      NaN  Volkswagen Eurovan
89  non-USA   Volkswagen Passat
90  non-USA  Volkswagen Corrado
91  non-USA           Volvo 240
92  non-USA           Volvo 850

[93 rows x 27 columns]

In [18]:
'''4. Write a program to create a summary report that includes information about the number of missing
values before and after forward fill and backward fill operations, as well as any specific patterns or trends
observed.'''
import pandas as pd

# Assuming 'data' is the DataFrame with missing values

# Summary report before forward fill
missing_before_forward_fill = data.isnull().sum()

# Perform forward fill
data_ffill = data.ffill()

# Summary report after forward fill
missing_after_forward_fill = data_ffill.isnull().sum()

# Perform backward fill
data_bfill = data.bfill()

# Summary report after backward fill
missing_after_backward_fill = data_bfill.isnull().sum()

# Create the summary report
summary_report = f"""
Summary Report:
----------------
Missing Values Before Forward Fill:
{missing_before_forward_fill}

Missing Values After Forward Fill:
{missing_after_forward_fill}

Missing Values After Backward Fill:
{missing_after_backward_fill}

Patterns or Trends Observed:
- Observations may vary based on the data characteristics and distribution.
- Forward fill fills missing values with the previous non-missing value in the column.
- Backward fill fills missing values with the next non-missing value in the column.
"""

print(summary_report)

Summary Report:
----------------
Missing Values Before Forward Fill:
Manufacturer           4
Model                  1
Type                   3
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        5
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         0
Luggage.room           0
Weight                 0
Origin                 5
Make                   3
dtype: int64

Missing Values After Forward Fill:
Manufacturer          0
Model                 0
Type                  0
Min.Price             0
Price                 0
Max.Price             0
MPG.city              0
MPG.highway           0
AirBags               1
DriveTrain            0
Cylinders             0
EngineSize            0
Horsepower            0
RPM                   0
Rev.per.mile          0
Man.trans.avail       0
Fuel.tank.capacity    0
Passengers            0
Length                0
Wheelbase             0
Width                 0
Turn.circle           0
Rear.seat.room        0
Luggage.room          0
Weight                0
Origin                0
Make                  0
dtype: int64

Missing Values After Backward Fill:
Manufacturer          1
Model                 0
Type                  0
Min.Price             0
Price                 0
Max.Price             0
MPG.city              0
MPG.highway           0
AirBags               0
DriveTrain            0
Cylinders             0
EngineSize            0
Horsepower            0
RPM                   0
Rev.per.mile          0
Man.trans.avail       0
Fuel.tank.capacity    0
Passengers            0
Length                0
Wheelbase             0
Width                 0
Turn.circle           0
Rear.seat.room        0
Luggage.room          0
Weight                0
Origin                0
Make                  0
dtype: int64

Patterns or Trends Observed:
- Observations may vary based on the data characteristics and distribution.
- Forward fill fills missing values with the previous non-missing value in the column.
- Backward fill fills missing values with the next non-missing value in the column.